Draft: Vcr tests continuation
Tomas2D/ibm-generative-ai pull request #5
Opened 2023-12-27 16:11 UTC by jezekra1

2023-12-27 17:03 UTC, Tomas2D requested changes

2023-12-27 17:03 UTC, Tomas2D commented on tests/features/models/cassettes/test_model_service/TestModelService.test_retrieve_model.yaml
> +      - BIGipServer~RIS3-INT-OCP-DAL12~Shared~ingress_fmaas_dev_fmaas_api=792414730.893.0000;
Remove

2023-12-27 17:03 UTC, Tomas2D commented on tests/features/prompt/cassettes/test_prompt_service/TestPromptService.test_create_delete_prompt.yaml
> +      Set-Cookie:
Remove

2023-12-27 17:03 UTC, Tomas2D commented on tests/features/prompt/cassettes/test_prompt_service/TestPromptService.test_create_delete_prompt.yaml
> +      Set-Cookie:
Remove

2023-12-28 08:03 UTC, jezekra1 commented on src/genai/features/text/generation/_generation_utils.py
> +def prompts_to_strings(
damn, forgot about this, thanks!

2023-12-28 08:20 UTC, jezekra1 commented on src/genai/features/text/chat/chat_generation_service.py
> -        self._limit = services.LimitService(api_client=api_client)
Do we want this limit also in the `ChatService`?
It wasn't used anywhere and chat doesn't have the async execution option.

2023-12-28 08:53 UTC, Tomas2D commented on src/genai/features/text/chat/chat_generation_service.py
> -        self._limit = services.LimitService(api_client=api_client)
Ohh, I see; keep it as is (removed).

2023-12-28 10:09 UTC, Tomas2D approved these changes

2023-12-28 10:09 UTC, merged