Fix extension tests
Tomas2D/ibm-generative-ai pull request #8
Opened 2024-01-03 17:06 UTC by jezekra1

2024-01-03 18:20 UTC, Tomas2D requested changes

2024-01-03 18:20 UTC, Tomas2D commented on src/genai/extensions/langchain/llm.py
> +        return _prepare_generation_request(**kwargs, **updated)
The user should know which parameters can be passed and which may not. I would remove this.

2024-01-03 18:20 UTC, Tomas2D commented on src/genai/extensions/langchain/utils.py
> +    for key, value in source.items():
This changes how the method works completely. Look at the `extract_token_usage` implementation.

2024-01-03 18:20 UTC, Tomas2D commented on src/genai/extensions/llama_index/llm.py
> +        chat_params_base.pop("data", None)
Rather than doing this, I would add the following property '_identifying_common_props`. 
I will also investigate if there is a plan to add `data` to the chat endpoint.

2024-01-03 18:20 UTC, Tomas2D commented on tests/assets/response_helper.py
> +                "stop_reason": "max_tokens" if idx == len(tokens) - 1 else "not_finished",
Interestingly, we do not have a `stop_reason` enum in the code. 
It looks like it's not part of the OpenAPI Schema. I will investigate that.

2024-01-03 18:20 UTC, Tomas2D commented on tests/integration/extensions/test_huggingface_agent.py
> +@pytest.mark.usefixtures("patch_generate_limits")
👍🏻

2024-01-03 18:20 UTC, Tomas2D commented on tests/integration/extensions/test_langchain.py
> +        httpx_mock.add_response(url=match_endpoint(TextGenerationCreateEndpoint), method="POST", json=GENERATE_RESPONSE)
What about switching to VCR?

2024-01-03 18:20 UTC, Tomas2D commented on tests/integration/extensions/test_langchain.py
> -        assert observed.llm_output["token_usage"]["generated_token_count"] == generated_token_count
`assert observed.llm_output["token_usage"] = { "prompt_tokens":  input_token_count, "completion_tokens": generated_token_count, "total_tokens": total_token_count}`

⬆️ will also tests that there is no extra property

2024-01-03 18:20 UTC, Tomas2D commented on tests/integration/extensions/test_llama_index.py
> +        assert result.additional_kwargs["token_usage"]["prompt_tokens"] == expected_result["input_token_count"]
I would use the same approach as above.

2024-01-03 19:14 UTC, Tomas2D commented on src/genai/extensions/llama_index/llm.py
> +        chat_params_base.pop("data", None)
It will not be added.

2024-01-04 08:14 UTC, jezekra1 commented on src/genai/extensions/langchain/utils.py
> +    for key, value in source.items():
There was a bug that all the extracted contents were zero, because the `source` here already contained the appropriate (extracted) keys

2024-01-04 08:18 UTC, jezekra1 commented on src/genai/extensions/langchain/llm.py
> +        return _prepare_generation_request(**kwargs, **updated)
There was a bug that the service got an unexpected kwarg parameter even if user did not fill it -> `execution_options: None` (from `self._identifying_params`). Maybe we can then drop all parameters from the resulting `kwargs` which are `None`. Same issue n multiple places

2024-01-04 08:20 UTC, jezekra1 commented on tests/integration/extensions/test_langchain.py
> +        httpx_mock.add_response(url=match_endpoint(TextGenerationCreateEndpoint), method="POST", json=GENERATE_RESPONSE)
I was thinking about it and I actually would be more confident if the responses were recorded instead of hard-coded. This way we have no idea if it still works with the API even if it passes with our mocks.

I'll see what I can do :)

2024-01-05 07:49 UTC, Tomas2D requested changes

2024-01-05 07:49 UTC, Tomas2D commented on tests/helpers.py
> +def parse_vcr_response_body(response: dict[str, Any]) -> dict[str, Any]:
Why do we need such a function instead of storing just a plain string response?

2024-01-05 07:49 UTC, Tomas2D commented on tests/integration/extensions/test_langchain.py
> +        [expected_response] = get_vcr_responses_of(TextGenerationCreateEndpoint)
I see; ideally, you want a deterministic result. What about tuning generation parameters to achieve such behaviour? Try to plain with `min_new_tokens` / `max_new_tokens` / `seed` / `temperature`.

2024-01-05 07:49 UTC, Tomas2D commented on tests/helpers.py
> +    elif content_type == "text/event-stream":
A parsing event stream is much more complex than what you showcase. For instance, the response has a retry mechanism or additional meta info.

2024-01-05 08:03 UTC, jezekra1 commented on tests/helpers.py
> +def parse_vcr_response_body(response: dict[str, Any]) -> dict[str, Any]:
This is parsing for the tests only, it doesn't change how we store the responses.
It's used in the `get_vcr_responses_of` fixture which is a helper similar to the `SimpleResponse` before, but instead of crafting the response ourselves, we leave the capture and storage of real response to VCR and we use it to assert that the features under test corectly parse it to the corresponding data structures (e.g. langchain).
The fixture acts kind of like a "spy proxy" on HTTPx responses.

2024-01-05 08:05 UTC, jezekra1 commented on tests/helpers.py
> +    elif content_type == "text/event-stream":
So far it's enough for the tests :) Let's extend it when necessary / when the tests break.
It's somewhat similar to this previous code:
```
        expected_generated_responses = [ChatStreamResponse(**result) for result in server_response]
        stream_responses = [f"data: {json.dumps(response)}\n\n".encode() for response in server_response]
        httpx_mock.add_response(
            url=match_endpoint(ServiceInterface.CHAT),
            stream=IteratorStream(stream_responses),
            headers={"Content-Type": "text/event-stream"},
        )
```

2024-01-05 08:06 UTC, jezekra1 commented on tests/integration/extensions/test_langchain.py
> +        [expected_response] = get_vcr_responses_of(TextGenerationCreateEndpoint)
I think I will remove this assert for now and just assert that langchain extension parsed correctly what was returned from the server

2024-01-05 08:06 UTC, jezekra1 commented on tests/integration/extensions/test_langchain.py
> +        [expected_response] = get_vcr_responses_of(TextGenerationCreateEndpoint)
Let's do deterministic tests on output separately if they're even necessary :)

2024-01-05 08:16 UTC, Tomas2D requested changes

2024-01-05 08:16 UTC, Tomas2D commented on src/genai/extensions/common/utils.py
>      request["parameters"] = parameters
```python
def _prepare_generation_request(parameters: Optional[TextGenerationParameters] = None, *, stop: Optional[list[str]] = None, **kwargs: Any):
    parameters = to_model_instance(parameters, TextGenerationParameters, copy=False)
    if stop is not None:
        parameters.stop_sequences = stop

    request = kwargs.copy()
    request["parameters"] = parameters
```

2024-01-05 08:16 UTC, Tomas2D commented on src/genai/extensions/langchain/llm.py
> +            "execution_options": dump_optional_model(self.execution_options),
Unexpected naming. Use shared property `_common_identifying_params` which will be used by this and the stream method.

2024-01-05 08:16 UTC, Tomas2D commented on src/genai/extensions/langchain/llm.py
> +        return _prepare_generation_request(**kwargs, **updated)
Comment above.

2024-01-05 08:16 UTC, Tomas2D commented on tests/integration/extensions/test_save_huggingface.py
> +        self.asset_path = pathlib.Path(__file__, "../..", "..", "assets").resolve()
`self.asset_path = pathlib.Path(__file__, "..", "...", "..", "assets").resolve()`
or
`self.asset_path = pathlib.Path(__file__, "../../..", "assets").resolve()`

2024-01-05 08:16 UTC, Tomas2D commented on tests/integration/extensions/test_llama_index.py
> +from src.genai.extensions.common.utils import create_generation_info_from_response
Probably wrong import (`src` ?).

2024-01-05 08:22 UTC, Tomas2D commented on tests/helpers.py
> +def parse_vcr_response_body(response: dict[str, Any]) -> dict[str, Any]:
I see; so what about using a parser for SSE via tooling exported from the `httpx-sse` library?

Library we use: https://github.com/florimondmanca/httpx-sse
Exported things related to our use case: `EventSource` / `connect_sse`

2024-01-05 08:22 UTC, Tomas2D commented on tests/helpers.py
> +    elif content_type == "text/event-stream":
I see; so what about using a parser for SSE via tooling exported from the httpx-sse library?

Library we use: https://github.com/florimondmanca/httpx-sse
Exported things related to our use case: EventSource / connect_sse

2024-01-05 08:33 UTC, jezekra1 commented on tests/integration/extensions/test_save_huggingface.py
> +        self.asset_path = pathlib.Path(__file__, "../..", "..", "assets").resolve()
thanks, this was Pycharm doing some automatic refactoring :D

2024-01-05 08:34 UTC, jezekra1 commented on tests/integration/extensions/test_save_huggingface.py
> +        self.asset_path = pathlib.Path(__file__, "../..", "..", "assets").resolve()
there is no test btw in this file 🤷

2024-01-05 09:28 UTC, jezekra1 commented on src/genai/extensions/langchain/llm.py
> +        return _prepare_generation_request(**kwargs, **updated)
Sorry, can you explain what you mean? This is an old diff, I changed it to:
```

    def _prepare_request(self, **kwargs):
        updated = {k: kwargs.pop(k, v) for k, v in self._identifying_params.items()}
        return _prepare_generation_request(**kwargs, **updated)

    def _prepare_stream_request(self, **kwargs):
        updated = {k: kwargs.pop(k, v) for k, v in self._identifying_stream_params.items()}
        return _prepare_generation_request(**kwargs, **updated)
 ```

2024-01-05 09:29 UTC, jezekra1 commented on tests/integration/extensions/test_save_huggingface.py
> +        self.asset_path = pathlib.Path(__file__, "../..", "..", "assets").resolve()
removed the file

2024-01-05 09:50 UTC, Tomas2D approved these changes
👍🏻 🚀

2024-01-05 09:51 UTC, merged